# Generated by Django 5.1.2 on 2024-11-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=255, null=1, unique=1),
            preserve_default=1,
        ),
    ]
