# Generated by Django 5.1.2 on 2024-11-15 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(null=1)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='post_content/')),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('slug_url', models.SlugField(max_length=25, null=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='Categories_App.categories')),
            ],
        ),
    ]
